# Generated by Django 3.1.2 on 2020-12-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201216_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgame',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
