# Generated by Django 3.1.2 on 2020-12-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_savedgame_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='savedGame',
        ),
    ]
